"""removed annotaion id from RootJob

Revision ID: c4c0f9d39103
Revises: 6661bde52ddf
Create Date: 2025-11-14 03:46:28.437254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c0f9d39103'
down_revision: Union[str, Sequence[str], None] = '6661bde52ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('root_jobs', 'segmentataion_annotation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('root_jobs', sa.Column('segmentataion_annotation_id', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
